#
#  Homebrew / OSX Package Installation
#
#  Author: Alex Howells <alex@howells.me>
#  Copyright (c) 2014, Alex Howells
#  Please see the LICENSE file in the repository root for further information.
#

# Make sure that we're usin the latest Homebrew (http://brew.sh)
update

# Taps
tap homebrew/binary
tap homebrew/completions
tap homebrew/dupes

# Bring any formulae which are installed up to date.
upgrade

#
# Installs (homebrew/main)
# Regular installs which are compiled from source...
#
install bash
install bash-completion
install fish
install fping
install git
install go
install hub
install mobile-shell
install mtr
install nmap
install node
install p7zip
install percona-server
install pwgen
install redis
install siege
install ssldump
install sslscan
install tcptraceroute
install tree
install tmux
install unrar
install wget --enable-iri
install zmap

#
# Installs (homebrew/binary)
# Things which are distributed as binary packages...
#
install packer

#
# Installs (homebrew/dupes)
# Things which duplicate OSX system packages ...
#
install homebrew/dupes/openssh

# Remove outdated versions
cleanup

# This essentially "chainloads" in all the Homebrew Cask stuff to avoid cluttering this file.
bundle Caskfile

